version: "3"

includes:
  gcp:
    taskfile: ./taskfiles/gcp.Taskfile.yaml
    dir: ./packages/gcp
  kubernetes:
    taskfile: ./taskfiles/kubernetes.Taskfile.yaml
    dir: ./packages/kubernetes
  qdrant:
    taskfile: ./taskfiles/qdrant.Taskfile.yaml
    dir: ./packages/qdrant
  agno:
    taskfile: ./taskfiles/agno.Taskfile.yaml
    dir: ./packages/agno

tasks:
  default: task --list-all

  install: uv sync --all-groups

  test:
    desc: Run all tests across all packages
    deps:
      - gcp:test
      - kubernetes:test
      - qdrant:test
      - agno:test

  format:
    desc: Format all Python code
    deps:
      - gcp:format
      - kubernetes:format
      - qdrant:format
      - agno:format

  check:
    desc: Run all checks (ruff + type checking)
    deps:
      - gcp:check
      - kubernetes:check
      - qdrant:check
      - agno:check
