version: "3"

includes:
  gcp:
    taskfile: ./taskfiles/gcp.Taskfile.yaml
    dir: ./packages/gcp
  anthropic:
    taskfile: ./taskfiles/anthropic.Taskfile.yaml
    dir: ./packages/anthropic
  openai:
    taskfile: ./taskfiles/openai.Taskfile.yaml
    dir: ./packages/openai

tasks:
  default: task --list-all

  install: uv sync --all-groups

  test:
    desc: Run all tests across all packages
    deps:
      - gcp:test
      - anthropic:test
      - openai:test

  format:
    desc: Format all Python code
    deps:
      - gcp:format
      - anthropic:format
      - openai:format

  check:
    desc: Run all checks (ruff + type checking)
    deps:
      - gcp:check
      - anthropic:check
      - openai:check
